### ISSUE TITLE
 error: 'struct NvDsInferTensorMeta' has no member named 'maintain_aspect_ratio'

### ISSUE THREAD

**Issue by qustions** [zhouyuchong/gst-nvinfer-custom#1]
after git clone I have changed all the make file paths to my paths but was getting this error. 
```
gstnvinfer_meta_utils.cpp: In function 'void attach_tensor_output_meta(GstNvInfer*, GstMiniObject*, GstNvInferBatch*, NvDsInferContextBatchOutput*)':
gstnvinfer_meta_utils.cpp:496:11: error: 'struct NvDsInferTensorMeta' has no member named 'maintain_aspect_ratio'
  496 |     meta->maintain_aspect_ratio = nvinfer->maintain_aspect_ratio;
      |           ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:54: gstnvinfer_meta_utils.o] Error 1

```
to solve this i have added `gboolean maintain_aspect_ratio; ` in `gstnvdsinfer.h` inside this struct `NvDsInferTensorMeta`
```
gboolean maintain_aspect_ratio;  
```

**Comment by qustions** [comment]
maybe you can add this in the readme

**Comment by zhouyuchong** [comment]
@qustions maintain_asptct_ratio is a property of `nvinfer` wittern by nvidia, check [here](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html#gst-nvinfer-file-configuration-specifications).
I didn't change this property, I only add the `user-meta` as well as `alignment`. Maybe there is some other reason to cause this error.
BTW, I'm using deepstream 6.1:dev docker. I just have a quick blink at ds 6.0 and find there ARE some differences but I don't sure whether it is the reason or not.
Since you compiled successfully, I think it's not a big problem.

**Comment by manhdoan291** [comment]
hi, i have an issue. I don't understand. I don't know where to put maintain_aspect_ratio inside this struct NvDsInferTensorMeta is to put it ?
How to fix it 
![Screenshot from 2022-10-14 09-21-17](https://user-images.githubusercontent.com/45356143/195747252-b8612fda-53a4-46e3-83dc-905886ab75b4.png)

**Comment by manhdoan291** [comment]
> @qustions maintain_asptct_ratio is a property of `nvinfer` wittern by nvidia, check [here](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html#gst-nvinfer-file-configuration-specifications). I didn't change this property, I only add the `user-meta` as well as `alignment`. Maybe there is some other reason to cause this error. BTW, I'm using deepstream 6.1:dev docker. I just have a quick blink at ds 6.0 and find there ARE some differences but I don't sure whether it is the reason or not. Since you compiled successfully, I think it's not a big problem.

Deepstream 6.1 no error. I can successfully with ds6.1 but ds6.0 have error about ['struct NvDsInferTensorMeta' has no member named 'maintain_aspect_ratio'](https://github.com/zhouyuchong/gst-nvinfer-custom/issues/1#top)
